* Bilkent-CS319
Object-Oriented Software Engineering Spring 2016

Group 8 Members(Alphabetical Order):
+ Ali Onur Geven - 21300896
+ Furkan Usta - 21301629
+ Furkan Salih Taşkale - 2130878
+ Halil Bülent Orhon - 21202096

** Reports:
[[file:CS319_Group8_Analysis_Report.pdf][Project Analysis Report (First Draft)]]

[[file:group8_cs319_AnalysisReport.pdf][Project Analysis Report (Revised)]]

[[file:cs319_group8_revised_analysis_report.pdf][Project Analysis Report (Final)]]

[[file:cs319_group8_design report.pdf][Project Design Report]]

[[file:design_report_final.pdf][Project Design Report (Revised)]]

** Description:
Our project is a game named "Conquest". It is a turn based multi-player strategy game (each player will play the game on same computer). Conquest will be played on the World Map and the main goal of the game is to be the Conqueror of the World. As the game starts areas on the map will be distributed randomly to each player. Each player will have different kinds of troops and every troop will have its own attributes. To be able to conquer the world players will have chances to create, upgrade troops and also attack to their neighbor areas. Players will gain gold for winning wars and they will spend this gold on upgrades and creation of troops. In each turn there will be limited number of upgrades and time spent. Whoever conquers the world will be the winner of the game.

References:
1-) https://en.wikipedia.org/wiki/Risk_(game)
